### ISSUE TITLE
Implement Xinanjiang runoff partitioning

### ISSUE THREAD

**Issue by SnowHydrology** [NOAA-OWP/cfe#10]
Add a runoff partitioning option by incorporating the Xinanjiang method.

## Current behavior

CFE uses the Schaake function to partition runoff.

## Expected behavior

CFE can be set to use Schaake _or_ Xinanjiang.

## Steps to replicate behavior (include URLs)

1. Copy code from @rlmcdaniel's dev branch (https://github.com/NOAA-OWP/alt-modular/tree/rlmcdaniel_dev/Modules/CFE) 
2. Implement as dev branch from `cfe/main`
3. Test
4. Merge with `cfe/main`

**Comment by jmframe** [comment]
jmframe's branch has made this change: https://github.com/jmframe/cfe
Review of code in progress before pull request is submitted.
