### ISSUE TITLE
Should `nash_storage_subsurface` & `nash_storage_surface`  be a 1d arrays of doubles?

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/cfe#124]
In the docs `nash_storage_subsurface` is listed as a double type, but in the parsing code, it looks like this should be a 1d array. @ajkhattak can you clarify this?

https://github.com/NOAA-OWP/cfe/blob/14f334a850981a564ee75b4181c2e9d4a74360b1/src/bmi_cfe.c#L1265

https://github.com/NOAA-OWP/cfe/blob/14f334a850981a564ee75b4181c2e9d4a74360b1/configs/README.md?plain=1#L25

**Comment by aaraney** [comment]
Looks like `nash_storage_surface` has the same issue.

**Comment by ajkhattak** [comment]
@aaraney you are right, they both should be 1D arrays, docs need to be updated...

**Comment by aaraney** [comment]
@ajkhattak, `nash_storage_subsurface` is optional too, right?

**Comment by ajkhattak** [comment]
> @ajkhattak, `nash_storage_subsurface` is optional too, right?

that is correct. I will get this issue fixed today.
