### ISSUE TITLE
CFE can sometimes destroy the world

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/cfe#31]
Running some of the tests in the CFE directory, I noticed that on occasion, CFE floods the earth to the catastrophic death of all its inhabitants.

## Current behavior
```
./run_cfe_bmi configs/cat_58_bmi_config_cfe.txt
Running CFE using Update
_____________________________
allocating memory to store entire BMI structure for CFE
Registering BMI CFE model
Initializeing BMI CFE model
Get the information from the configuration here in Main
looping through and calling update
#    ,            hourly ,  direct,   giuh ,lateral,  base,   total
#Time,           rainfall,  runoff,  runoff, flow  ,  flow,  discharge
# (h),             (mm)   ,  (mm) ,   (mm) , (mm)  ,  (mm),    (mm)
1 0.000000 0.000000 0.000000 0.000000 191.086232 191.086232
2 0.000000 0.000000 0.000000 0.000000 177.384014 177.384014
3 0.000000 0.000000 0.000000 0.002266 165.504231 165.506496
4 0.000000 0.000000 0.000000 0.006533 155.101951 155.108484
5 0.000000 0.000000 0.000000 0.012558 145.914744 145.927302
6 0.000000 0.000000 0.000000 0.020117 137.739285 137.759402
7 0.000000 0.000000 0.000000 0.029005 130.415524 130.444529
8 0.000000 0.000000 0.000000 0.039033 123.815700 123.854733
9 0.000000 0.000000 0.000000 0.050030 117.836555 117.886585
10 0.000000 0.000000 0.000000 0.061837 112.393703 112.455541
11 0.000000 0.000000 0.000000 0.074311 107.417488 107.491799
12 0.000000 0.000000 0.000000 0.087320 102.849890 102.937211
13 0.000000 0.000000 0.000000 0.100745 98.642185 98.742930
14 85.099998 48.042466 2.882548 0.114478 94.798485 97.795511
15 195.400009 149.798919 33.489593 0.128420 91.284938 124.902951
16 220.000000 177.850638 100.520378 0.143337 88.058453 188.722168
17 264.700012 225.633278 151.950616 0.160099 85.083034 237.193748
18 276.500000 241.223906 198.761729 0.179390 82.327289 281.268409
19 395.200012 362.183930 233.768590 0.201737 79.766006 313.736333
20 345.600006 316.083481 303.633019 0.227503 77.376180 381.236702
21 268.200012 241.735781 312.834090 0.256944 75.138397 388.229431
22 120.599998 98.430021 268.393213 0.290191 73.034599 341.718003
23 21.000000 9.410704 167.245507 0.327270 71.043157 238.615934
24 0.000000 0.000000 70.850663 0.368088 69.144593 140.363344
25 0.000000 0.000000 21.698673 0.412301 67.332672 89.443646
26 0.000000 0.000000 4.082185 0.459320 65.601714 70.143220
27 0.000000 0.000000 0.282321 0.508610 63.946532 64.737463
28 0.000000 0.000000 0.000000 0.559681 62.362379 62.922060
29 0.000000 0.000000 0.000000 0.612090 60.844900 61.456990
30 0.000000 0.000000 0.000000 0.665435 59.390092 60.055527
31 0.000000 0.000000 0.000000 0.719352 57.994270 58.713623
32 0.000000 0.000000 0.000000 0.773515 56.654033 57.427548
33 0.000000 0.000000 0.000000 0.827627 55.366238 56.193865
34 0.000000 0.000000 0.000000 0.881426 54.127973 55.009399
35 0.000000 0.000000 0.000000 0.934675 52.936540 53.871215
36 0.000000 0.000000 0.000000 0.987165 51.789432 52.776597
37 0.000000 0.000000 0.000000 1.038711 50.684317 51.723028
38 72.500000 41.791157 2.507469 1.089148 49.640408 53.237025
39 168.600006 130.659733 29.153074 1.138334 48.657885 78.949293
40 130.800003 98.107828 84.224458 1.186852 47.728283 133.139593
41 157.500000 125.944077 99.191301 1.235387 46.846841 147.273529
42 164.699997 135.307877 116.753046 1.284423 46.008606 164.046075
43 145.100006 118.421378 127.069373 1.334359 45.208784 173.612516
44 126.900002 102.463945 122.485469 1.385492 44.443380 168.314341
45 98.500000 76.468630 110.017983 1.438017 43.708700 155.164699
GLOBAL MASS BALANCE
  initial volume:   8.5856 m
    volume input:   3.2569 m
   volume output:   6.5298 m
    final volume:   5.1750 m
        residual: 6.1062e-16 m
global pct. err: 1.8749e-14 percent of inputs
 DIRECT RUNOFF MASS BALANCE
  surface runoff:   2.6996 m
    infiltration:   0.5573 m
direct residual: -2.2204e-16 m
 GIUH MASS BALANCE
  vol. into giuh:   2.6996 m
   vol. out giuh:   2.5618 m
 vol. end giuh q:   0.0000 m
   giuh residual: -2.7756e-16 m
 SOIL WATER CONCEPTUAL RESERVOIR MASS BALANCE
   init soil vol:   0.5856 m
  vol. into soil:   0.5573 m
vol.soil2latflow:   0.1836 m
 vol. soil to gw:   0.2234 m
 final vol. soil:   0.7360 m
vol. soil resid.: 2.7756e-17 m
 NASH CASCADE CONCEPTUAL RESERVOIR MASS BALANCE
    vol. to nash:   0.1836 m
  vol. from nash:   0.0224 m
 final vol. nash:   0.1612 m
nash casc resid.: 2.7756e-17 m
 GROUNDWATER CONCEPTUAL RESERVOIR MASS BALANCE
init gw. storage:   8.0000 m
       vol to gw:   0.2234 m
     vol from gw:   3.7844 m
final gw.storage:   4.4389 m
    gw. residual: 8.8818e-16 m
Finalizing CFE model
Running CFE using UPDATE UNTIL
```
So far, so good!
```
_____________________________
allocating memory to store entire BMI structure for CFE
Registering BMI CFE model
Initializeing BMI CFE model
Get the information from the configuration here in Main
The model time step size is: 3600.000000
Calling update_until()
#    ,            hourly ,  direct,   giuh ,lateral,  base,   total
#Time,           rainfall,  runoff,  runoff, flow  ,  flow,  discharge
# (h),             (mm)   ,  (mm) ,   (mm) , (mm)  ,  (mm),    (mm)
45 0.000000 73418116346661979634657007168926831317265721499937011074726989597754276029363696239152237209512845188504587502541593269231888082309452745940097146610041472075610007033925873199743663922893771943088797578979625917333005758627840.000000 155.164699 111.476811 0.000000 110.017983
Finalizing CFE model
```
Not so good.

## Expected behavior

With an hourly rainfall of 0.000000 mm, CFE shouldn't destroy all life on earth.

## Steps to replicate behavior (include URLs)
Run `./run_cfe_bmi configs/cat_58_bmi_config_cfe.txt` multiple times...

This does appear to be the result of undefined behavior.  It is not consistent in the output, and may take several runs of the same binary to produce.  I will note that is most likely due to some uninitialized memory somewhere in either the BMI code or the CFE source, and some systems will try to 0 memory when it is allocated, which will hide this bug on those systems, but this can't be depended on.

**Comment by SnowHydrology** [comment]
Are you happy now @hellkite500? Look at what you've made me do:
![image](https://user-images.githubusercontent.com/32177682/142489846-7955ee71-e8d5-4300-a634-5d92f96ae0ca.png)

**Comment by SnowHydrology** [comment]
It only took two runs back to back for that to happen.

**Comment by SnowHydrology** [comment]
Could it just be an issue with the main that runs via update_until after running with update?

**Comment by hellkite500** [comment]
@SnowHydrology I don't think so, I see the same behavior running it through ngen.  But to verify that it wasn't some issue with the framework, I went to the source and reproduced it.

**Comment by SnowHydrology** [comment]
Hmm, I deleted the update_until bits out of main and can run many times without that error showing up. Does the error show up for you if you use update?

**Comment by hellkite500** [comment]
@SnowHydrology I think this issue still exists regardless of whether `update_until` is called.  Looking closely at [the implementation](https://github.com/NOAA-OWP/cfe/blob/e8c2d4b0391cec7d4191beb16f8c10650e3e02e2/src/bmi_cfe.c#L1010), I verified that it only ever iterates and calls `Update(self)` 45 times (0 - 44).  And I don't see anything else in `update_until` that could possibly manipulate the model state.  So the issue occurs via `Update`.

It might be that it is more easily triggered in update_until simply due to memory allocation/layout when that function is used.

**Comment by jmframe** [comment]
Darn it. @SnowHydrology , it looks like you have errors in the precip and the direct runoff, but @hellkite500 only has error in the direct runoff? @SnowHydrology your time step size is 1800... I am not reproducing the result... event with: `for i in {1..500}; do ./run_cfe_bmi ./configs/cat_58_bmi_config_cfe.txt; done`...

**Comment by hellkite500** [comment]
> I am not reproducing the result... event with: `for i in {1..500}; do ./run_cfe_bmi ./configs/cat_58_bmi_config_cfe.txt; done`... 

@jmframe what kind of system are you running on?

**Comment by jmframe** [comment]
Cheyenne.

**Comment by hellkite500** [comment]
Do you have access to any other machine? It seems easy to trigger on a Mac...

**Comment by jmframe** [comment]
I can see if I can figure out how to run on mac. But that will have to wait. Ummm... But one thing that comes to mined is that the update_until version will run the precipitation value that is initialized over and over again. So could be an issue with this: https://github.com/NOAA-OWP/cfe/blob/e8c2d4b0391cec7d4191beb16f8c10650e3e02e2/src/bmi_cfe.c#L921

**Comment by hellkite500** [comment]
> update_until version will run the precipitation value that is initialized over and over again.

Doesn't `Update` advance the time index? Still worth looking to ensusre all variables are properly initialized.

**Comment by jmframe** [comment]
Oh yeah, that's right. I was thinking in `cfe_ptr->is_forcing_from_bmi == TRUE` mode. But it failed in the mode where it reads forcings from the file and indexes them as well...?

**Comment by SnowHydrology** [comment]
> Darn it. @SnowHydrology , it looks like you have errors in the precip and the direct runoff, but @hellkite500 only has error in the direct runoff? @SnowHydrology your time step size is 1800... I am not reproducing the result... event with: `for i in {1..500}; do ./run_cfe_bmi ./configs/cat_58_bmi_config_cfe.txt; done`...

That was just one version of the error. I ran it multiple times and sometimes the errors manifested differently. I even got -0.0000 as a precip value for one run. However, I only ever got the wonky numbers in precipitation or direct runoff.

My time step is 1800 because I was also testing what happens when you change the hard-coded time step. It's not good so we should put a warning comment next to where the time step is assigned in the model.

> Oh yeah, that's right. I was thinking in `cfe_ptr->is_forcing_from_bmi == TRUE` mode. But it failed in the mode where it reads forcings from the file and indexes them as well...?

Mine failed when running `make_and_run_bmi.sh`.

> Do you have access to any other machine? It seems easy to trigger on a Mac...

I'm not Jonathan, but I'm on a Mac and can definitely confirm it's a problem.

**Comment by hellkite500** [comment]
Ok, so one problem identified to avoid potential world ending catastrophe.

The driver code was printing from the wrong bmi/cfe model [here](https://github.com/NOAA-OWP/cfe/blob/e8c2d4b0391cec7d4191beb16f8c10650e3e02e2/src/main.c#L108).  This should be `cfe_main_data2` and not `cfe_main_data`.

However, I'm still unable to produce consistent results.  I modified the driver locally to only run a single `Update` and to run `Update_until` for just a single timestep.  These should be functionally the same, since `Update_until` calls `Update` exactly once.

But sometimes, the result from `Update_until` is not consistent between runs, and when it isn't, it is also not consistent with the result of `Update` in the same driver run.

**Comment by hellkite500** [comment]
![image](https://user-images.githubusercontent.com/5186647/142666990-8e09b4c8-61bd-4989-9033-decf5b699290.png)
Turns out, just not as likely to destroy the world, but I think I may have pinpointed the issue...

**Comment by stcui007** [comment]
I don't have the problem on ucs2. There is apparently a loop in main.c that
set to be less than 45.
