### ISSUE TITLE
Model execution routine does not use received ET values

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/cfe#35]
When CFE is used via the BMI functions (and I suspect also in standalone mode), its `extern void cfe` function, defined in _src/cfe.c_, is called.  One of the parameters this `extern void  cfe` function receives is:

`struct evapotranspiration_structure *evap_struct`

This struct has several members, in particular `potential_et_m_per_s`.  The `evap_struct->potential_et_m_per_s` member is being set with the expected ET value when running the module via BMI.

(An aside: only this one member of the struct seems to be getting set, or even initialized, but it's not apparent whether this is directly causing any problems.)

However, the `evap_struct` param is never actually used within the function.  A grep on the file shows that the only place it appears is where it is declared in the function signature:

```
nwcal-mbook7632:ngen robert.bartel$ grep -n evap_struct extern/cfe/cfe/src/cfe.c
40:        struct evapotranspiration_structure *evap_struct,
nwcal-mbook7632:ngen robert.bartel$ 
```

**Comment by SnowHydrology** [comment]
Both `et_from_soil` and `et_from_rainfall` are provided as functions in cfe.c, but similar to @robertbartel's note on `evap_struct` above, neither of them are called by `cfe`.

https://github.com/NOAA-OWP/cfe/blob/4ff498473720f2614f64325df1ec79c8a8579640/src/cfe.c#L691

https://github.com/NOAA-OWP/cfe/blob/4ff498473720f2614f64325df1ec79c8a8579640/src/cfe.c#L664

**Comment by SnowHydrology** [comment]
@jmframe, see my comment above. It seems like the `et_from_*` calls should come before the partitioning calls. Please let me know if that's consistent with your understanding of CFE.

https://github.com/NOAA-OWP/cfe/blob/4ff498473720f2614f64325df1ec79c8a8579640/src/cfe.c#L79

**Comment by madMatchstick** [comment]
For reference, both `et_from_rainfall` and `et_from_soil` are called in the python version's `run_cfe()` [here](https://github.com/NOAA-OWP/cfe/blob/4ff498473720f2614f64325df1ec79c8a8579640/py_cfe/cfe.py#L22) and [here](https://github.com/NOAA-OWP/cfe/blob/master/py_cfe/cfe.py#L36).

**Comment by jmframe** [comment]
Oh Yeah. They got lost between cfe reviews with Fred. Oops. They should be implemented in the order of the Python version that Jess linked. So et_from_rainfall, then direct_runoff, then et_from_soil. Sorry for that oversight.

**Comment by hellkite500** [comment]
@robertbartel will need to update the ngen cfe submodule.

**Comment by robertbartel** [comment]
@madMatchstick @SnowHydrology @jmframe @hellkite500 please confirm my assessment, but I don't believe #36 resolves this.  

In the BMI execution I traced through, only the `evap_struct->potential_et_m_per_s` member of that ET struct was being set.  The `evap_struct->potential_et_m_per_timestep` was not being set or initialized, and the `et_from_rainfall` and `et_from_soil` functions only uses `potential_et_m_per_timestep`.  

Again, please let me know if I've missed something on this, but based on that it appears that the externally set ET values are still not going to be utilized.

**Comment by hellkite500** [comment]
@robertbartel You are correct.  #36 calls the routines in the backend CFE model, but it doesn't address the initialization and updating of the `evap_struct`.

**Comment by jmframe** [comment]
Somewhere per_s needs to be converted to per_timestep: https://github.com/NOAA-OWP/cfe/blob/023b794f599e48984e5f2f99f70cdfcc82e3f29b/py_cfe/cfe.py#L17

**Comment by madMatchstick** [comment]
See [update](https://github.com/NOAA-OWP/cfe/commit/92f253654494d810115d1d37d97607128a159903) per jmframe comment.
