### ISSUE TITLE
Parameter setting for groundwater and soil moisture reservoirs

### ISSUE THREAD

**Issue by RY4GIT** [NOAA-OWP/cfe#38]
Hi, I am Ryoko Araki, a Ph.D. student at San Diego State University, and trying to use this model for my thesis project (calibrating CFE with soil moisture data). My advisor, Dr. McMillan, introduced me to this repository. I have a question about parameter settings for groundwater and soil moisture reservoirs. 

## Current behavior
- Parameters for groundwater and soil reservoirs are pre-set in [cfe/py_cfe/bmi_cfe.py](https://github.com/NOAA-OWP/cfe/blob/master/py_cfe/bmi_cfe.py) (L186-206) 
- Two of the parameters (Cgw and expon for groundwater reservoir) are included in the input configuration [cfe/py_cfe/cat_58_config_cfe.json](https://github.com/NOAA-OWP/cfe/blob/master/py_cfe/cat_58_config_cfe.json)

## Expected behavior
I wonder that isn't it more straightforward that all parameters (coeff_primary, expon_primary, coeff_secondary, and expon_secondary) are controllable from the input file for both reservoirs (groundwater and soil reservoirs). 
They are pre-set or not controllable because (a) the model is still under development, or (b) the parameters are not influential to the results, or (c) the parameters are related to intrinsic physical properties? 
I would like to know because I want to try changing soil reservoir parameters. 

I am sorry if it is not appropriate to throw an issue on the model under development.

**Comment by SnowHydrology** [comment]
Hello @RY4GIT, thank you for tagging this issue. You are correct that the hard-coded values had been carried over from the development version of the model. We will work on an upgrade that converts those parameters to be settable by the user.

Please don't hesitate to follow up. Thanks!

**Comment by RY4GIT** [comment]
Hello @SnowHydrology, thank you very much for quick response. I will keep an eye on the development!

**Comment by lcunha0118** [comment]
Hi @RY4GIT , An additional reason is that CFE uses the fundamental equations from NOAH-MP in a lumped fashion. Therefore, for parameters values we are using the parameters from the current version of the NWM (https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/nwm.v2.1.6/parm/). The parameters that are in the config file are the ones that are available from the NWM. The hard-coded ones are ones that are not currently available from the NWM set. 
I agree with @SnowHydrology , all parameters should eventually be included in the config file.

**Comment by SnowHydrology** [comment]
Hello @RY4GIT, I'm reopening this issue because that's how we track improvements, bug fixes, etc. Please feel free to comment on this issue or open a new one if you notice anything else. Thanks!

**Comment by RY4GIT** [comment]
@lcunha0118 Thank you for the follow-up! I see, that makes sense. When I try out the model, I will keep eyes on the differentiation. 
@SnowHydrology I got it, and thanks! I will try the model out and will see how it goes!

**Comment by madMatchstick** [comment]
@RY4GIT - Thank you again for your engagement. These parameter settings have been adjusted and [merged](https://github.com/NOAA-OWP/cfe/pull/42) for the Python version of CFE.

**Comment by RY4GIT** [comment]
Thank you very much!
