### ISSUE TITLE
Bug in variable name: soil_reservoir_storage_deficit --> soil_reservoir_storage_deficit_m

### ISSUE THREAD

**Issue by RY4GIT** [NOAA-OWP/cfe#53]
Hello,

soil_reservoir_storage_deficit in L55 in cfe/py_cfe/cfe.py should be soil_reservoir_storage_deficit**_m**
https://github.com/NOAA-OWP/cfe/blob/74ce510842234c2c3ec7d90fe590f19c8cdbd49a/py_cfe/cfe.py#L55

I will try creating a pull request soon. 

Best regards,
Ryoko

**Comment by RY4GIT** [comment]
Created a pull-request, please kindly review it. @SnowHydrology, thank you very much for teaching me how to use Github!

**Comment by hellkite500** [comment]
Will leave this issue open until the fix is approved and merged or otherwise decided that this isn't needed! Thanks for you contribution!

**Comment by RY4GIT** [comment]
Hi, thank you for your prompt reply and I am sorry I will not close an issue by myself next time!

**Comment by hellkite500** [comment]
No worries, you are welcome to close any issues that are resolved, just didn't want this to get lost until it is resolved! We will link it to the PR you submitted and it should close automatically once that is merged.

**Comment by RY4GIT** [comment]
I got it, thank you!!
