### ISSUE TITLE
CFE standalone mode with option FORCINGPET

### ISSUE THREAD

**Issue by WanruWu-NOAA** [NOAA-OWP/cfe#75]
Following the README.md for Compiling and Running CFE with option FORCINGPET in standalone mode it didn't pass the run . I was wondering if I missed anything and/or how to fix it?

## Steps to replicate behavior (include URLs)

1. git clone https://github.com/NOAA-OWP/cfe.git
2.   cd cfe
3.   git checkout ajk/sft_aet_giuh_merge
4.   mkdir build && cd build
5.   cmake ../ -DFORCINGPET=ON
6.   make
7. ./run_cfe.sh FORCINGPET 
8. Run results and error messages:
```
CFE running with option FORCINGPET
config file: ./configs/cat_87_bmi_config_cfe_pass.txt ./configs/cat_87_bmi_config_aorc.txt ./configs/cat_87_bmi_config_pet_pass.txt
allocating memory to store entire BMI structure for CFE
allocating memory to store entire BMI structure for AORC
allocating memory to store entire BMI structure for PET
Registering BMI CFE model
Registering BMI AORC model
Registering BMI PET model
Initializeing BMI CFE model
' could not be opened for reading
Initializeing BMI AORC model
AORC config file ./configs/cat_87_bmi_config_aorc.txt
File does not exist.
 Failed in function read_file_line_counts
' could not be opened for readinggs/cat87_01Dec2015.csv
Initializeing BMI PET model
File does not exist.
 Failed in function read_file_line_counts_pet
' could not be opened for reading
Get the information from the configuration here in Main
forcing file for the CFE module BMI
forcing file for the PET module BMI
forcing file for the AORC module ./forcings/cat87_01Dec2015.csv
The model time step size is: 3600.000000
looping through and calling update
#    ,            hourly ,  direct,   giuh ,lateral,  base,   total, storage, ice fraction, ice fraction
Time [h],rainfall [mm],runoff [mm],runoff [mm],flow [mm],flow [mm],discharge [mm],storage [mm],schaake [mm],xinan [-]
./run_cfe.sh: line 38: 88456 Segmentation fault      (core dumped) ./build/${exe_name} $args
```

**Comment by ajkhattak** [comment]
@WanruWu-NOAA yeah the README.md needs to be updated. We don't need step #3. You should be able to run with the following instructions. Let me know if you see any issues.
1. git clone https://github.com/NOAA-OWP/cfe.git
2. cd cfe
3. mkdir build && cd build
4. cmake ../ -DFORCINGPET=ON
5. make
6. ./run_cfe.sh FORCINGPET

**Comment by WanruWu-NOAA** [comment]
@ajkhattak Thanks for looking into this. I've retested the steps, it's making progress but still some errors:

**Comment by ajkhattak** [comment]
Does not look to me that you are running the default examples. The issue is coming from a missing file.
**File does not exist.
 Failed in function read_file_line_counts
' could not be opened for readinggs/cat87_01Dec2015.csv**
While it should have stopped the execution at that point and let the user know what is happening, anyway, can you please check if this file **readinggs/cat87_01Dec2015.csv** exists? did you mean **readings** or **readinggs**

**Comment by WanruWu-NOAA** [comment]
I was confused about this error message too - no idea how "**readinggs**" came from running `./run_cfe.sh FORCINGPET`? I did check the file `cat87_01Dec2015.csv`, which was under directory `/forcings/` and directory `/original_author_code/` But I couldn't find "**readinggs**"....

**Comment by WanruWu-NOAA** [comment]
Finally, the "Download Zip" version CFE works! Although my "git clone" version is still not working, we are good now to move forward. Thanks a lot for your help, Ahmad!

**Comment by ajkhattak** [comment]
this is a good workaround for you to run cfe. A better option would be to download `git` to your home directory and check if that will work or not. I am still not sure why your `git clone` is not working properly.
